# Generated by Django 4.2.3 on 2024-04-04 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ブロックID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="削除日")),
                (
                    "blocked_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_for",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ブロック先ユーザー",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_from",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ブロック元ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ブロック",
            },
        ),
    ]
