# Generated by Django 4.2.3 on 2025-06-17 04:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_pinged_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ping_log',
            },
        ),
    ]
